name: zfanz_electronics
description: ZFANZ - Watch & Download after Pay 200 UGX
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.5
  video_player: ^2.8.2
  dio: ^5.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  youtube_player_flutter: ^9.0.3
  http: ^1.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
